version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass Redis2022!
    ports:
      - "6379:6379"
    expose:
      - 6379
  backend:
    image: github-explorer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis
